# -*- coding: utf-8 -*-
"""Phase 3: Targeted cleanup of remaining narrative English in ch6-8."""
from docx import Document
import re

doc = Document(r"E:\项目\project_code\paper_outputs\draft\final_chinese_academic_format.docx")
def st(idx, text):
    doc.paragraphs[idx].text = text

# Additional replacements for narrative English (not field names)
reps2 = [
    ("replay readiness", "重放准备能力"),
    ("replay mismatch", "重放不一致"),
    ("expected trace", "预期轨迹"),
    ("claimed trace", "声称轨迹"),
    ("trace steps", "轨迹步数"),
    ("challenge timeout", "挑战超时"),
    ("max bisection rounds", "最大二分轮次"),
    ("rounds", "轮次"),
    ("payload publication", "负载发布"),
    ("full_onchain_", "全链上_"),
    ("full_onchain_gas", "全链上燃料"),
    ("target_gas", "目标燃料"),
    ("onchain gas per byte", "链上单字节燃料"),
    ("da gas per byte", "数据可用性单字节燃料"),
    ("DA-bound", "数据可用性绑定"),
    ("DA-bound compact commit", "数据可用性绑定的紧凑提交"),
    ("modular DA", "模块化数据可用性"),
    ("verifiable DA", "可验证数据可用性"),
    ("ledger entries", "账本条目"),
    ("onchain gas", "链上燃料"),
    ("response tampering", "响应篡改"),
    ("attestation invalid", "远程证明无效"),
    ("attestation_invalid", "远程证明无效"),
    ("response_tampered", "响应篡改"),
    ("trace_length_mismatch", "轨迹长度不匹配"),
    ("challenge_timeout_no_recover", "超时不可恢复"),
    ("challenge_timeout_recover", "超时可恢复"),
    ("da_unavailable", "数据不可用"),
    ("da_proof_invalid", "数据可用性证明无效"),
    ("detection rate", "检测率"),
    ("challenge success", "挑战成功率"),
    ("slashing rate", "罚没比例"),
    ("recovery success", "恢复成功率"),
    ("challenge success rate", "挑战成功率"),
    ("slashed rate", "罚没比例"),
    ("recovery history", "恢复历史"),
    ("recovery count", "恢复次数"),
    ("replay evidence", "重放证据"),
    ("proof evidence", "证明证据"),
    ("DA proof", "数据可用性证明"),
    ("DA entry", "数据可用性条目"),
    ("DA profile", "数据可用性配置"),
    ("DA fetch", "数据可用性取回"),
    ("Merkle verification", "Merkle 证明验证"),
    ("Merkle proof", "Merkle 证明"),
    ("Merkle root", "Merkle 根"),
    ("payload hash", "负载哈希"),
    ("state_root", "状态根"),
    ("output_hash", "输出哈希"),
    ("proof_hash", "证明哈希"),
    ("da_pointer", "数据可用性指针"),
    ("da_merkle_root", "数据可用性 Merkle 根"),
    ("expected hash", "预期哈希"),
    ("claimed hash", "声称哈希"),
    ("expected_hash", "预期哈希"),
    ("claimed_hash", "声称哈希"),
    ("narrowing_complete", "缩小完成"),
    ("replay_executed", "重放已执行"),
    ("replay_passed", "重放已通过"),
    ("challenge_success", "挑战成功"),
    ("resolution_bits", "结算位"),
    ("mismatch_bits", "不一致位"),
    ("target_step", "目标步数"),
    ("watchdog node", "观察节点"),
    ("recoverable state machine", "可恢复状态机"),
    ("recoverable challenge", "可恢复挑战机制"),
    ("timeout workload", "超时工作负载"),
    ("failure taxonomy", "故障分类"),
    ("comparison experiments", "对比型实验"),
    ("comparison-oriented", "对比型"),
    ("synthetic ledger", "合成账本"),
    ("synthetic workload", "合成工作负载"),
    ("synthetic trace", "合成轨迹"),
    ("synthetic timeout", "合成超时"),
    ("simulated environment", "模拟环境"),
    ("simulated setup", "模拟设置"),
    ("local EVM", "本地以太坊虚拟机"),
    ("local chain", "本地链"),
    ("on-chain commit", "链上提交"),
    ("off-chain proof", "链下证明"),
    ("off-chain data", "链下数据"),
    ("on-chain data", "链上数据"),
    ("on-chain contract", "链上合约"),
    ("on-chain footprint", "链上痕迹"),
    ("on-chain footprint", "链上开销"),
    ("on-chain overhead", "链上开销"),
    ("onchain footprint", "链上开销"),
    ("full calldata", "完整调用数据"),
    ("full onchain", "全链上"),
    ("full_onchain", "全链上"),
    ("compact commit", "紧凑提交"),
    ("compact commitment", "紧凑提交"),
    ("compact external", "紧凑外部"),
    ("compact EIP", "紧凑类 EIP"),
    ("compact modular", "紧凑模块化"),
    ("external DA", "外部数据可用性"),
    ("calldata pricing", "调用数据定价"),
    ("blob pricing", "blob 定价"),
    ("transaction congestion", "交易拥堵"),
    ("target_step", "目标步数"),
    ("replay_executed", "重放执行"),
    ("trace_length", "轨迹长度"),
    ("replay_passed", "重放通过"),
    ("resolution_bits", "结算位"),
    ("mismatch_bits", "不一致位"),
    ("payload_bytes", "负载字节数"),
    ("full_bytes", "完整字节数"),
    ("compact_bytes", "紧凑字节数"),
    ("prompt length", "提示长度"),
    ("gas cost", "燃料成本"),
    ("gas reduction", "燃料降幅"),
    ("reduction ratio", "降幅比例"),
    ("replay-ready readiness", "重放准备能力"),
    ("replay readiness", "重放准备能力"),
    ("narrowing complete", "缩小完成"),
    ("challenge session", "挑战会话"),
    ("dispute range", "争议区间"),
    ("single step", "单步"),
    ("bisection round", "二分轮次"),
    ("timestamp", "时间戳"),
    ("slashing logic", "罚没逻辑"),
    ("resolution logic", "结算逻辑"),
    ("arbitration path", "仲裁路径"),
    ("arbitration flow", "仲裁流程"),
    ("evidence entry", "证据入口"),
    ("evidence structure", "证据结构"),
    ("evidence association", "证据关联"),
    ("evidence binding", "证据绑定"),
    ("evidence loading", "证据加载"),
    ("evidence chain", "证据链"),
    ("evidence context", "证据上下文"),
    ("mismatch detection", "不一致检测"),
    ("state transition", "状态转移"),
    ("state machine", "状态机"),
    ("fault path", "故障路径"),
    ("fault detection", "故障检测"),
    ("fault recovery", "故障恢复"),
    ("fault handling", "故障处理"),
    ("slashing path", "罚没路径"),
    ("slashing mechanism", "罚没机制"),
    ("timeout window", "超时窗口"),
    ("timeout timer", "超时计时器"),
    ("timeout session", "超时会话"),
    ("timeout recovery", "超时恢复"),
    ("timeout detection", "超时检测"),
    ("timeout scenario", "超时场景"),
    ("timeout overhead", "超时开销"),
    ("timeout handling", "超时处理"),
    ("timeout behavior", "超时行为"),
    ("replay window", "重放窗口"),
    ("replay phase", "重放阶段"),
    ("replay stage", "重放阶段"),
    ("replay process", "重放过程"),
    ("replay path", "重放路径"),
    ("replay result", "重放结果"),
    ("replay check", "重放检查"),
    ("replay verification", "重放验证"),
    ("replay logic", "重放逻辑"),
    ("replay flow", "重放流程"),
    ("replay capability", "重放能力"),
    ("replay context", "重放上下文"),
    ("replay correctness", "重放正确性"),
    ("commitment binding", "承诺绑定"),
    ("payload commitment", "负载承诺"),
    ("commitment scheme", "承诺方案"),
    ("byte cost", "字节成本"),
    ("byte overhead", "字节开销"),
    ("byte reduction", "字节降幅"),
    ("amortized cost", "摊销成本"),
    ("amortized overhead", "摊销开销"),
    ("cost overhead", "成本开销"),
    ("cost structure", "成本结构"),
    ("cost profile", "成本配置"),
    ("cost boundary", "成本边界"),
    ("cost trend", "成本趋势"),
    ("cost model", "成本模型"),
    ("cost argument", "成本论证"),
    ("cost reduction", "成本降幅"),
    ("cost saving", "成本节省"),
    ("cost estimate", "成本估算"),
    ("cost estimation", "成本估算"),
    ("cost behavior", "成本行为"),
    ("batch effect", "批处理效应"),
    ("batch parameter", "批处理参数"),
    ("batch scenario", "批处理场景"),
    ("batch setting", "批处理设置"),
    ("batch processing", "批处理"),
    ("deployment record", "部署记录"),
    ("deployment evidence", "部署证据"),
    ("deployment boundary", "部署边界"),
    ("deployability evidence", "可部署性证据"),
    ("contract counterpart", "合约对应物"),
    ("contract path", "合约路径"),
    ("contract deployment", "合约部署"),
    ("contract address", "合约地址"),
    ("contract interface", "合约接口"),
    ("gas measurement", "燃料测量"),
    ("gas baseline", "燃料基线"),
    ("gas estimate", "燃料估算"),
    ("gas profile", "燃料配置"),
    ("gas overhead", "燃料开销"),
    ("gas behavior", "燃料行为"),
    ("gas cost", "燃料成本"),
    ("gas usage", "燃料用量"),
    ("gas reduction", "燃料降幅"),
    ("gas reduction ratio", "燃料降幅比例"),
    ("gas difference", "燃料差异"),
    ("gas trend", "燃料趋势"),
    ("gas behavior", "燃料行为"),
    ("per-byte gas", "单字节燃料"),
    ("recover overhead", "恢复开销"),
    ("recover capability", "恢复能力"),
    ("recover mechanism", "恢复机制"),
    ("recover path", "恢复路径"),
    ("recover flow", "恢复流程"),
    ("recover operation", "恢复操作"),
    ("recover function", "恢复函数"),
    ("recover logic", "恢复逻辑"),
    ("recover call", "恢复调用"),
    ("recover scenario", "恢复场景"),
    ("recover success", "恢复成功"),
    ("recover failure", "恢复失败"),
    ("recover rate", "恢复率"),
    ("recover ratio", "恢复比例"),
    ("recover cost", "恢复成本"),
    ("recover gas", "恢复燃料"),
    ("recover window", "恢复窗口"),
    ("recover boundary", "恢复边界"),
    ("recover semantics", "恢复语义"),
    ("recover property", "恢复性质"),
    ("recover guarantee", "恢复保证"),
    ("recover liveness", "恢复活性"),
    ("recover safety", "恢复安全性"),
    ("recover correctness", "恢复正确性"),
    ("proof field", "证明字段"),
    ("proof membership", "证明成员关系"),
    ("proof verification", "证明验证"),
    ("proof check", "证明检查"),
    ("proof path", "证明路径"),
    ("proof integrity", "证明完整性"),
    ("proof binding", "证明绑定"),
    ("proof chain", "证明链"),
    ("proof association", "证明关联"),
    ("attestation verification", "远程证明验证"),
    ("attestation check", "远程证明检查"),
    ("attestation binding", "远程证明绑定"),
    ("attestation chain", "远程证明链"),
    ("attestation field", "远程证明字段"),
    ("attestation evidence", "远程证明证据"),
    ("attestation path", "远程证明路径"),
    ("attestation verification", "远程证明验证"),
    ("attestation nonce", "远程证明随机数"),
    ("attestation signature", "远程证明签名"),
    ("attestation digest", "远程证明摘要"),
    ("attestation output", "远程证明输出"),
    ("attestation record", "远程证明记录"),
    ("attestation scheme", "远程证明方案"),
    ("attestation format", "远程证明格式"),
    ("challenge path", "挑战路径"),
    ("challenge flow", "挑战流程"),
    ("challenge mechanism", "挑战机制"),
    ("challenge logic", "挑战逻辑"),
    ("challenge process", "挑战过程"),
    ("challenge phase", "挑战阶段"),
    ("challenge state", "挑战状态"),
    ("challenge result", "挑战结果"),
    ("challenge outcome", "挑战结果"),
    ("challenge evidence", "挑战证据"),
    ("challenge context", "挑战上下文"),
    ("challenge behavior", "挑战行为"),
    ("challenge property", "挑战性质"),
    ("challenge liveness", "挑战活性"),
    ("challenge safety", "挑战安全性"),
    ("challenge correctness", "挑战正确性"),
    ("challenge completion", "挑战完成"),
    ("challenge progression", "挑战推进"),
    ("challenge overhead", "挑战开销"),
    ("challenge cost", "挑战成本"),
    ("challenge gas", "挑战燃料"),
    ("challenge protection", "挑战保护"),
    ("challenge defense", "挑战防御"),
    ("payload field", "负载字段"),
    ("payload data", "负载数据"),
    ("payload size", "负载大小"),
    ("payload content", "负载内容"),
    ("payload integrity", "负载完整性"),
    ("payload verification", "负载验证"),
    ("payload retrieval", "负载取回"),
    ("payload check", "负载检查"),
    ("payload proof", "负载证明"),
    ("payload binding", "负载绑定"),
    ("payload commitment", "负载承诺"),
    ("payload hash", "负载哈希"),
    ("payload pointer", "负载指针"),
    ("payload entry", "负载条目"),
    ("payload structure", "负载结构"),
    ("payload format", "负载格式"),
    ("payload storage", "负载存储"),
    ("payload publication", "负载发布"),
    ("payload scaling", "负载规模扩展"),
    ("full payload", "完整负载"),
    ("compact submission", "紧凑提交"),
    ("compact structure", "紧凑结构"),
    ("compact format", "紧凑格式"),
    ("compact proof", "紧凑证明"),
    ("compact representation", "紧凑表示"),
    ("compact size", "紧凑大小"),
    ("compact object", "紧凑对象"),
    ("liveness property", "活性性质"),
    ("liveness guarantee", "活性保证"),
    ("liveness analysis", "活性分析"),
    ("liveness continuity", "活性连续性"),
    ("liveness recovery", "活性恢复"),
    ("safety property", "安全性质"),
    ("safety guarantee", "安全保证"),
    ("safety analysis", "安全性分析"),
    ("safety boundary", "安全边界"),
    ("safety argument", "安全论证"),
    ("safety claim", "安全主张"),
    ("safety requirement", "安全要求"),
    ("correctness property", "正确性性质"),
    ("correctness guarantee", "正确性保证"),
    ("correctness analysis", "正确性分析"),
    ("correctness boundary", "正确性边界"),
    ("correctness check", "正确性检查"),
    ("correctness verification", "正确性验证"),
    ("correctness argument", "正确性论证"),
    ("security property", "安全性质"),
    ("security analysis", "安全性分析"),
    ("security argument", "安全论证"),
    ("security guarantee", "安全保证"),
    ("security boundary", "安全边界"),
    ("security claim", "安全主张"),
    ("security model", "安全模型"),
    ("security assumption", "安全假设"),
    ("security requirement", "安全要求"),
    ("security property", "安全性质"),
]

# Apply to all paragraphs
count = 0
for i, p in enumerate(doc.paragraphs):
    text = p.text
    for eng, chn in reps2:
        if eng in text:
            text = text.replace(eng, chn)
            count += 1
    if text != p.text:
        doc.paragraphs[i].text = text

print(f"P3 paragraph replacements: {count}")

# Apply to table cells
tcount = 0
for table in doc.tables:
    for row in table.rows:
        for cell in row.cells:
            for para in cell.paragraphs:
                text = para.text
                for eng, chn in reps2:
                    if eng in text:
                        text = text.replace(eng, chn)
                        tcount += 1
                if text != para.text:
                    para.text = text

print(f"P3 table replacements: {tcount}")

# Fix "bytes" in narrative (not in field names like "full_bytes")
# Do targeted fixes
for i, p in enumerate(doc.paragraphs):
    text = p.text
    # Fix "X bytes" patterns
    text = re.sub(r'(\d+\.?\d*)\s*bytes', r'\1 字节', text)
    text = re.sub(r'(\d+\.?\d*)\s*byte', r'\1 字节', text)
    if text != p.text:
        doc.paragraphs[i].text = text

doc.save(r"E:\项目\project_code\paper_outputs\draft\final_chinese_academic_format.docx")
print("Phase 3 complete.")
